name: Docker Build and Push

on:
  push:
    paths:
      - 'BE/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: ./BE
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/was .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image
      working-directory: BE
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/was
